---
name: GHCR image retention

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete >1month old untagged images
    permissions:
      contents: read
      packages: write
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "docker-debian13-ansible"
          tag-selection: untagged
          cut-off: 1month
          dry-run: true
