---
name: GHCR image retention

on:
  workflow_dispatch:
  schedule:
    - cron: "12 2 * * 0"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete untagged images
    steps:
      - name: Cleanup registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
